### ISSUE TITLE
Storage account connections do not use https by default

### ISSUE THREAD

**Issue by z7paul** [Kentico/AzureStorageProvider#10]
### Brief bug description

By default the storage account connection uses http.
In CloudBlobClient.cs:
var account = new Microsoft.WindowsAzure.Storage.CloudStorageAccount(credentials, false);

However, new Azure storage accounts are created with a default of Secure transfer required = Enabled.
This means http storage account requests result in 400 Bad Request responses.

### Expected behavior
Connections should be made using https by default.
i.e. var account = new Microsoft.WindowsAzure.Storage.CloudStorageAccount(credentials, true);

**Comment by ondrabus** [comment]
Fixed in 75337654fe2b587dcefa1bbaae4c16503a8be1d1
