### ISSUE TITLE
FileHandler.cs (CMSPages/GetAzureProviderFile.aspx) does not set correct mime type

### ISSUE THREAD

**Issue by z7paul** [Kentico/AzureStorageProvider#11]
### Brief bug description

In the FileHandler.cs (CMSPages/GetAzureProviderFile.aspx), the mime type is being incorrectly set (based on the path)
i.e. SetResponseContentType(path);

### Expected behavior

The SetResponseContentType method is expecting a mime type.
e.g. SetResponseContentType(MimeMapping.GetMimeMapping(path));

**Comment by ondrabus** [comment]
Fixed in 75337654fe2b587dcefa1bbaae4c16503a8be1d1
