### ISSUE TITLE
Add Kentico 12 Support

### ISSUE THREAD

**Issue by z7paul** [Kentico/AzureStorageProvider#12]
### Motivation

Add support for Kentico 12

### Proposed solution
- Reference Kentico.Libraries 12.x.x nuget package
- Update service resolution syntax, e.g. Service.Resolve&lt;IInterface&gt;();
- Update storage synchronization task calls
e.g. LogUpdateFileTask, LogDirectoryDeleteTask,LogDeleteFileTask
(CMS.IO.StorageHelper -> CMS.IO.StorageSynchronization)

Note: CMS.IO.StorageSynchronization is an internal class, so the access modifier will need to be changed by Kentico in the assembly.  
Alternatively, reflection may be used as a workaround.

**Comment by ondrabus** [comment]
Fixed in 75337654fe2b587dcefa1bbaae4c16503a8be1d1
