### ISSUE TITLE
Path does not start with file system prefix

### ISSUE THREAD

**Issue by interestinglive** [Kentico/AzureStorageProvider#2]
Hi,

Thanks for the code - awesome.

We used it in a fresh v11.0 install however and when we went to select the favicon (from Settings -> Content), which we had uploaded to the media library we where experiencing the "Path does not start with file system prefix" error thrown from line 55 of Helpers\AzurePathHelper.cs:

https://github.com/Kentico/AzureStorageProvider/blob/43a4f52909104ed1171219cbfd859d8cee5b6261/k10/src/AzureStorageProvider/Helpers/AzurePathHelper.cs#L55

This was stopping the dialog from loading.

I've just changed that to return a empty string for the moment and that seemed to bring it all back online however just thought I'd raise it and see if anybody else has run into that issue?

**Comment by petrsvihlik** [comment]
Hi @interestinglive , thanks for submitting this. @ondrabus is on a vacation, he'll reply as soon as he gets back.

**Comment by ondrabus** [comment]
Hi @interestinglive, thank you for submitting this issue and steps to reproduce it. It is now fixed.
