### ISSUE TITLE
Make the project dependent on Kentico.Libraries NuGet package

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/AzureStorageProvider#5]
### Motivation

Currently, it's required to copy the `Lib` folder in order to make the AzureStorageProvider work.

https://github.com/Kentico/AzureStorageProvider/blame/master/README.md#L16

### Proposed solution

To get rid of the manual step, the project should reference the [Kentico.Libraries](https://www.nuget.org/packages/Kentico.Libraries/) NuGet package.

**Comment by KristianJakubik** [comment]
Hi, I would like to work on this.

**Comment by ondrabus** [comment]
@KristianJakubik thank you for your interest. Please accept the invite.
