### ISSUE TITLE
Can't select template file name from Page Template definition dialog

### ISSUE THREAD

**Issue by interestinglive** [Kentico/AzureStorageProvider#6]
### Brief bug description

In the "Select File" dialog when setting up an ASPX template the dialog doesn't show any files, just folders.

### Repro steps

1. Go to Page templates
2. Select Blank ASPX -> Master page template
3. Click Select in the File name dialog

![select file](https://user-images.githubusercontent.com/1525045/45669166-76419a00-bb62-11e8-85ac-c8a53de72d06.JPG)

### Expected behavior

We expect to be able to choose the local file.

**Comment by ondrabus** [comment]
Hi @interestinglive,
can you please try the new package (uploaded just now) with up-to-date libraries? I can not reproduce this locally.
Thanks.

**Comment by interestinglive** [comment]
I've tried and still have the same issues - any pointers on where I can look to troubleshoot?

**Comment by ondrabus** [comment]
Are you mapping the whole file system to Azure or just specific folders? You can enable logs in Settings -> System -> Debug and see in Event log which folders and files are listed from Azure.

**Comment by interestinglive** [comment]
I guess I'm just doing whatever is default in the DLL as I haven't changed it. How would I choose to only map a specific folder?

**Comment by interestinglive** [comment]
Looks like it's doing the whole file system - Sorry about this, but I can't find any options in the instructions.docx for only mapping a particular folder through the config. Am I missing something?

**Comment by interestinglive** [comment]
I think I've got a workaround for whatever is causing this locally - I've modified the  OnInit of AzureStorageProviderModule to specify two providers - one the default Windows filesystem provider and the other specifically for the media library. Then it's working as I expected.

` if (SettingsHelper.AppSettings[nameof(WebConfigKeys.CMSStorageProviderAssembly)] == "AzureStorageProvider")
            {
                var azureprovider = new StorageProvider("AzureStorageProvider", "AzureStorageProvider", true);
                StorageHelper.MapStoragePath(SettingsHelper.AppSettings["CMSAzureStorageRoot"], azureprovider);

                var provider = new StorageProvider(null, "CMS.FileSystemStorage", true);
                StorageHelper.MapStoragePath("/", provider);

            }
`
Thanks for the code - awesome

**Comment by ondrabus** [comment]
It's not possible to reproduce this issue on k12 provider, therefore closing.
